"""create devices, sensor_readings, fused_events tables

Revision ID: 0cde05ac022f
Revises: 
Create Date: 2026-09-22 10:44:16.493557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cde05ac022f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_table('fused_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'anomaly', 'insufficient_data', name='fusion_status_enum'), nullable=False),
    sa.Column('fused_distance_m', sa.Float(), nullable=True),
    sa.Column('discrepancy_m', sa.Float(), nullable=True),
    sa.Column('source_reading_ids', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fused_events_device_time', 'fused_events', ['device_id', 'event_time'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('sensor_type', sa.Enum('radar', 'tof', 'gps', name='sensor_type_enum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_time', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_readings_device_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index('ix_fused_events_device_time', table_name='fused_events')
    op.drop_table('fused_events')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###

    # NOT auto-generated — added by hand. Postgres ENUM types are separate
    # database objects, not part of the table that uses them, so dropping
    # a table does NOT drop the enum type it referenced. Without this,
    # downgrading then upgrading again fails with "type already exists"
    # (verified by actually running downgrade -> upgrade while building
    # this migration). Order matters here too: a type can't be dropped
    # while a column still references it, so this runs after both
    # drop_table calls above.
    sa.Enum(name='sensor_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='fusion_status_enum').drop(op.get_bind(), checkfirst=True)
